name: Format and lint checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  typescript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "format"
        run: |
          npm install
          npm run format -c
      - name: "lint"
        run: |
          npm run lint
