name: Format and lint checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: "lint"
        run: |
          npm install
          npm run lint
