name: Test that the action fails if benchmark increase exceeds threshold
on:
  workflow_dispatch:
  pull_request:
jobs:
  run-action-exceed-threshold:
    runs-on: ubuntu-latest
    steps:
      # run the test using the local action in repo
      - uses: actions/checkout@v4
      - name: "build"
        run: |
          npm install
          npm run build
      - uses: ./ # local action in repo
        # First add the data from part 1
        with:
          name: 'Test fail if exceed threshold'
          input-data-path: ./test/data/extract/testFailPart1.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          gh-pages-branch: gh-pages-test
          group-by: 'os,keySize'
          schema: 'os,keySize,name,platform,api,category'
      - uses: ./ # local action in repo
        # Then add the data from part 2, which represents
        # more than a 200% increase.
        with:
          name: 'Test fail if exceed threshold'
          input-data-path: ./test/data/extract/testFailPart2.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          gh-pages-branch: gh-pages-test
          group-by: 'os,keySize'
          schema: 'os,keySize,name,platform,api,category'
          fail-on-alert: true
          alert-threshold: 200%
  # ensure that the above job fails
  check-action-fails-on-exceed-threshold:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [run-action-exceed-threshold]
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing
        if: ${{ (contains(needs.*.result, 'failure')) }}
        run: exit 1
