name: Run TypeScript tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  typescript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: "build and test"
        run: |
          npm install
          npm run build
          npm run test
